[package]
name = "fishgame"
version = "0.1.0"
authors = ["Fedor Logachev <not.fl3@gmail.com>"]
edition = "2018"

[dependencies]
nanoserde = "0.1"
macroquad = { git = "https://github.com/not-fl3/macroquad.git" }
physics-platformer = { git = "https://github.com/not-fl3/macroquad.git" }
macroquad-tiled = { git = "https://github.com/not-fl3/macroquad.git" }
macroquad-particles = { git = "https://github.com/not-fl3/macroquad.git", features = ["nanoserde"] }
macroquad-profiler = { git = "https://github.com/not-fl3/macroquad.git" }
bitfield = "0.13"
#nakama_sdk = { path = "../nakama_sdk" }
nakama_sdk = { path = "https://github.com/jojolepro/nakama_sdk" }
lazy_static = "*"

[target.'cfg(target_arch = "wasm32")'.dependencies]
sapp-jsutils = "0.1"

[patch.crates-io]
macroquad = { git = "https://github.com/not-fl3/macroquad.git" }

# [patch.'https://github.com/not-fl3/macroquad.git']
# macroquad = { path = "../macroquad" }
# macroquad-particles = { path = "../macroquad/particles" }
# physics-platformer = { path = "../macroquad/physics-platformer" }
# macroquad-profiler = { path = "../macroquad/profiler" }

# [patch.crates-io]
# macroquad = { path = "../macroquad" }
# miniquad = { path = "../miniquad" }
# megaui = { path = "../megaui" }
# sapp-jsutils = { path = "../sapp-jsutils" }
